['guest.common.erp.getMedicineInfoListForErp']
type = "timeout"
backend_url = "http://127.0.0.1:18080"
timeout_ms = 90
#status_code = 200
#content_type = "application/json; charset=utf-8"
resp_body = '''
{
    "code": 10,
    "msg": "time out downgraded",
    "result": []
}
'''

['guest.st_api.getStoreInfo']
type = "callback"
backend_url = "http://127.0.0.1:18080"
callback_url = "http://192.168.1.1:8281/handle_callback"
#callback_credentials_header = "X-Callback-Credentials"
#status_code = 200
#content_type = "application/json; charset=utf-8"
resp_body = '''
{
    "code": 11,
    "msg": "callback downgraded",
    "result": ""
}
'''
